
server:
    port: 8099
    servlet:
        encoding:
            force-response: true


spring:
    thymeleaf:
#        view-names: thymeleaf/*
        prefix: classpath:/templates/
        suffix: .html
        cache: false
        encoding: UTF-8
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        sql-script-encoding: UTF-8
        url: jdbc:mariadb://localhost:3306/aging_demographics?useUnicode=true&characterEncoding=utf8&charSet=UTF-8
        username: root
        password: root1111

mybatis:
    mapper-locations: mybatis/mapper/**/**.xml

